"""QEMU + Vagrant execution-substrate backend.

The QEMU backend is the **extended-realism** tier in AutoSUT's substrate
hierarchy (canonical Docker -> extended QEMU -> experimental Tart). It
provisions a real virtual machine (real kernel boundary, real virtual NIC,
real filesystem layout) via Vagrant with the QEMU provider — the same path
the frozen ``sticks/Vagrantfile`` adopts for Apple Silicon hosts and the
libvirt path uses on Linux hosts.

Why this exists
---------------

A reviewer asking "does AutoSUT really exercise the OS kernel boundary, or
is everything a container abusing the host kernel?" needs a yes/no answer.
With this backend, the answer for any campaign declaring
``backend: qemu`` in its SUT profile is *yes*: the OS kernel is loaded from
a guest disk image, syscalls cross the hypervisor, and the network stack is
fully virtualised.

The Docker path remains canonical (portable, low cost, identical
orchestration semantics). The QEMU path is opt-in for techniques that need
the strictly stronger isolation guarantees of a real VM.

Reproducibility contract
------------------------

- Host requirements: ``vagrant`` + ``qemu`` + ``vagrant-qemu`` plugin on
  macOS ARM64. On Linux, ``vagrant-libvirt`` + ``qemu-kvm`` is the
  equivalent path; the orchestrator works the same way once provider is
  installed.
- Guest image: public, signed Ubuntu cloud image referenced by box name in
  the per-run Vagrantfile. No custom-built boxes (deliberate — keeps the
  artifact reproducible from a clean clone).
- One Vagrant project per campaign run, under
  ``release/evidence/<run>/qemu/vagrant_project/``. The orchestrator
  ``destroy``s the VM on teardown (no shared state, no warm-lab reuse) so
  every run is cold-start and self-contained.
- Provisioning time is deliberately bounded at run level: by default the
  base image already carries the packages the SUT profile lists, but a
  per-run cloud-init can install the few missing ones if necessary.

Performance note
----------------

QEMU cold-start on Apple Silicon (HVF acceleration) is ~30-60 s per run
versus ~2 s for Docker. That cost is acceptable for the realism dividend
and is documented in :doc:`/CAMPAIGN_ORCHESTRATION` so a TPC reviewer can
budget it.
"""

from __future__ import annotations

import shutil
import subprocess
import uuid
from pathlib import Path

from .environment_base import CommandResult, EnvironmentBackend
from .models import SUTProfile


# A public ARM64-friendly Ubuntu 22.04 box. Falls back to the canonical
# ``ubuntu/jammy64`` x86_64 box when running on an x86_64 host where the
# provider is libvirt or virtualbox.
_BOX_ARM64 = "perk/ubuntu-2204-arm64"
_BOX_X86_64 = "ubuntu/jammy64"


# Inline Vagrantfile written per-run. Kept minimal so the file is easy for
# a reviewer to audit. The {placeholders} are filled by Python f-string at
# bring_up time.
_VAGRANTFILE_TEMPLATE = """# -*- mode: ruby -*-
# Auto-generated by AutoSUT QEMUEnvironment for run {run_id}.
# Reviewers can audit this file alongside the manifest under
# release/evidence/{run_id}/qemu/.

Vagrant.configure("2") do |config|
  config.vm.box = "{box}"
  config.vm.box_check_update = false
  config.vm.hostname = "autosut-{run_id_short}"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 600
  config.ssh.insert_key = true

  config.vm.provider "qemu" do |qe|
    qe.arch = "aarch64"
    qe.machine = "virt,accel=hvf"
    qe.cpu = "host"
    qe.memory = "{memory_mb}"
    qe.smp = {smp}
    qe.net_device = "virtio-net-pci"
  end

  config.vm.provider "libvirt" do |lv|
    lv.memory = {memory_mb}
    lv.cpus = {smp}
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = {memory_mb}
    vb.cpus = {smp}
  end
end
"""


def _is_apple_silicon() -> bool:
    import platform as _platform
    return _platform.machine().lower() in {"arm64", "aarch64"}


def _vagrant_available() -> bool:
    return shutil.which("vagrant") is not None


class QEMUEnvironment(EnvironmentBackend):
    """One Vagrant+QEMU VM provisioned for a single campaign run.

    Contract identical to :class:`DockerEnvironment` — bring up, run shell,
    teardown — so the orchestrator and executor are substrate-agnostic.
    """

    backend_name = "qemu"

    def __init__(self, project_dir: Path, sut: SUTProfile, run_dir: Path):
        self.project_dir = project_dir
        self.sut = sut
        self.run_dir = run_dir

    @property
    def host_id(self) -> str:
        # Vagrant uses "default" when only one VM is defined.
        return f"vagrant-default@{self.project_dir.name}"

    @classmethod
    def bring_up(cls, sut: SUTProfile, run_dir: Path) -> "QEMUEnvironment":
        if not _vagrant_available():
            raise RuntimeError(
                "QEMUEnvironment requires `vagrant` on PATH. Install via "
                "`brew install vagrant qemu` and `vagrant plugin install "
                "vagrant-qemu` on macOS ARM64, or `apt install vagrant "
                "qemu-kvm libvirt-daemon-system` + `vagrant plugin install "
                "vagrant-libvirt` on Linux."
            )
        project_dir = run_dir / "qemu" / "vagrant_project"
        project_dir.mkdir(parents=True, exist_ok=True)

        box = _BOX_ARM64 if _is_apple_silicon() else _BOX_X86_64
        run_id_short = uuid.uuid4().hex[:8]
        vagrantfile = _VAGRANTFILE_TEMPLATE.format(
            box=box,
            memory_mb=sut.memory_mb,
            smp=sut.smp,
            run_id=run_dir.name,
            run_id_short=run_id_short,
        )
        (project_dir / "Vagrantfile").write_text(vagrantfile, encoding="utf-8")

        setup_log = run_dir / "sut" / "setup.log"
        setup_log.parent.mkdir(parents=True, exist_ok=True)
        setup_log.write_text(
            f"# QEMU VM bring-up\nbox: {box}\nproject_dir: {project_dir}\n"
            f"memory_mb: {sut.memory_mb}\nsmp: {sut.smp}\n",
            encoding="utf-8",
        )

        # `vagrant up` is the cold-start point; do not background it.
        proc = subprocess.run(
            ["vagrant", "up", "--provider", _default_provider()],
            cwd=project_dir, capture_output=True, text=True,
            check=False, timeout=900,
        )
        with setup_log.open("a", encoding="utf-8") as fh:
            fh.write(f"\n--- vagrant up stdout ---\n{proc.stdout}\n"
                     f"--- vagrant up stderr ---\n{proc.stderr}\n"
                     f"exit_code: {proc.returncode}\n")
        if proc.returncode != 0:
            raise RuntimeError(
                f"`vagrant up` failed (exit {proc.returncode}). See "
                f"{setup_log}. First 600 chars of stderr:\n{proc.stderr[:600]}"
            )
        return cls(project_dir, sut, run_dir)

    def run_shell(self, command: str, log_name: str | None = None,
                  timeout: int = 600) -> CommandResult:
        """Execute ``command`` inside the VM via ``vagrant ssh``.

        We deliberately use ``vagrant ssh -c`` (which uses Vagrant's managed
        key) rather than wiring up a separate SSH client. That keeps the
        backend dependency-free beyond Vagrant itself.
        """
        proc = subprocess.run(
            ["vagrant", "ssh", "-c", command],
            cwd=self.project_dir, capture_output=True, text=True,
            timeout=timeout,
        )
        result = CommandResult(
            cmd=command, exit_code=proc.returncode,
            stdout=proc.stdout, stderr=proc.stderr,
        )
        if log_name:
            log_path = self.run_dir / log_name
            log_path.parent.mkdir(parents=True, exist_ok=True)
            log_path.write_text(
                f"$ {command}\n"
                f"exit_code: {result.exit_code}\n"
                f"--- stdout ---\n{result.stdout}\n"
                f"--- stderr ---\n{result.stderr}\n",
                encoding="utf-8",
            )
        return result

    def teardown(self) -> bool:
        proc = subprocess.run(
            ["vagrant", "destroy", "-f"],
            cwd=self.project_dir, capture_output=True, text=True,
            check=False, timeout=120,
        )
        log_path = self.run_dir / "sut" / "teardown.log"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        log_path.write_text(
            f"vagrant destroy -f\nexit_code: {proc.returncode}\n"
            f"stdout: {proc.stdout}\nstderr: {proc.stderr}\n",
            encoding="utf-8",
        )
        return proc.returncode == 0


def _default_provider() -> str:
    """Pick the vagrant provider name appropriate for the current host."""
    if _is_apple_silicon():
        return "qemu"
    # On Linux, default to libvirt; users on x86_64 macOS can override.
    return "libvirt"
